import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24"></main>
  );
}
